



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

module TypeWriter.Templates {
    
    /**
     * Interface for: Starterkit.Web.BL.ViewModels.BaseDTO
     */
     export interface IBaseDTO {
        
        Id: number;
    }

    /**
     * Base view model for Starterkit.Web.BL.ViewModels.BaseDTO
     */
    export class BaseDTO  implements IBaseDTO  {
         
        Id: number;

        constructor() {
          //nothing
        }
    }
}