

//*************************DO NOT MODIFY*************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY*************************

module TypeWriter.Templates {

    
    export enum Category {
        Red = 0,
        Blue = 1,
        Green = 2,
    }
    
    export enum Availability {
        InStock = 0,
        OutOfStock = 1,
        BackOrdered = 2,
    }
    
}