



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

module TypeWriter.Templates {
    
    /**
     * Interface for: Starterkit.Web.BL.ViewModels.ProductSearchCriteriaDTO
     */
     export interface IProductSearchCriteriaDTO {
        
        Id: number;
        Name: string;
    }

    /**
     * Base view model for Starterkit.Web.BL.ViewModels.ProductSearchCriteriaDTO
     */
    export class ProductSearchCriteriaDTO  implements IProductSearchCriteriaDTO  {
         
        Id: number;
        Name: string;

        constructor() {
          //nothing
        }
    }
}