



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************

module TypeWriter.Templates {
    
    /**
     * Interface for: Starterkit.Web.BL.ViewModels.ProductDTO
     */
     export interface IProductDTO extends IBaseDTO{
        
        DisplayName: string;
        CreatedDate: Date;
        ModifiedDate: Date;
        Category: Category;
        Availability: Availability;
    }

    /**
     * Base view model for Starterkit.Web.BL.ViewModels.ProductDTO
     */
    export class ProductDTO extends BaseDTO implements IProductDTO  {
         
        DisplayName: string;
        CreatedDate: Date;
        ModifiedDate: Date;
        Category: Category;
        Availability: Availability;

        constructor() {
          super();
        }
    }
}