

/// <reference path="../typings/jquery/jquery.d.ts" />

//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
module TypeWriter.Templates {
    
    export class Startup {
        public _baseUrl: string;

        constructor(baseUrl: string){
            this._baseUrl = baseUrl;
        }

        
        // post: api/Startup/
        private RouteConfigureServices = () => `${this._baseUrl}api/Startup/`;
        public configureServices(services: ServiceDescriptor[]): JQueryPromise<void> {
            return $.ajax({
                url: this.RouteConfigureServices(),
                type: 'post',
                data: services
            });
        }
        // post: api/Startup/
        private RouteConfigure = () => `${this._baseUrl}api/Startup/`;
        public configure(app: IApplicationBuilder, env: IHostingEnvironment): JQueryPromise<void> {
            return $.ajax({
                url: this.RouteConfigure(),
                type: 'post',
                data: { app: app, env: env }
            });
        }
    }
}